apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 74.2.2 # chart-version
      helm:
        valueFiles:
          - $values/envs/dev2/apps/monitoring/prometheus-stack/values-of-prometheus-stack.yaml
    - repoURL: https://github.com/StepanLem/k8s-my-postinstall.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      #- ServerSideApply=true чат гпт добавил
      # Без этой штуки высирает ошибку, что: crd не могут скачаться из-за слишком большого размера.
      # обсуждения ошибки и ограничения argocd описываются если гуглить:
      # "prometheus stack one or more synchronization tasks completed unsuccessfully, reason: CustomResourceDefinition.apiextensions.k8s."
      # У этой ошибки есть два решения проблемы:
      # а) ServerSideApply=true # минус этого способа? Оф доку надо прочесть.
      # б) вручную sync(with replace) несинхронизированные ресурсы(то есть crd)


      