apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.gitlab.io
      chart: gitlab-runner
      targetRevision: 0.81.0 # chart-version
      helm:
        valueFiles:
          - $values/envs/dev2/apps/gitlab-runner/values-of-gitlab-runner.yaml
    - repoURL: https://github.com/StepanLem/k8s-my-postinstall.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true




