apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources: # кстати если интересно git - к закрытым репо, к которым ssh доступ есть, а https к публичным обычно.
    - repoURL: git@gitlab.com:transcriber-app/nginx-frontend.git # репо с чартом.
      targetRevision: main
      path: charts/nginx-frontend # путь до чарта в репо с чартом.
      helm:
        valueFiles:
          - $values/envs/dev/apps/1.transcriber/nginx-frontend/values.yaml # путь до values в репо с values.
    - repoURL: https://github.com/StepanLem/k8s-my-postinstall.git # репо с vaules.
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
