image:
  repository: registry.gitlab.com/transcriber-app/nginx-frontend
  pullPolicy: IfNotPresent
  tag: v0.0.3

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: frontend.veryred.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nginx-frontend-tls
      hosts:
        - frontend.veryred.ru