image:
  tag: v0.0.30
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: frontend.veryred.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nginx-frontend-tls
      hosts:
        - frontend.veryred.ru
