# PostgreSQL configuration for development environment

# версию и values смотри на артифкатхаб:
# https://artifacthub.io/packages/helm/bitnami/postgresql

# Global configuration
global:
  postgresql:
    auth:
      postgresPassword: "a" # пароль для admin
      username: "a" # не шифруется
      password: "a" # пароль для user
      database: "a" # не шифруется
      # existingSecret: "" # тут ты передаёшь имя секрета
      # secretKeys: # а тут ключи в этом секрете
      #   adminPasswordKey: ""
      #   userPasswordKey: ""
      #   replicationPasswordKey: ""

architecture: standalone # или replication

# Используем legacy репозиторий Bitnami для решения проблемы с ImagePullBackOff 
# как минимум для чарта версии 16.7.26 это проблема
image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: 17.6.0-debian-12-r0
  pullPolicy: IfNotPresent

# Primary PostgreSQL configuration
primary:  
  persistence:
    enabled: true
    # existingClaim: "" # заполнить это и остальное будет игнорироваться.
    size: 8Gi
    storageClass: local-path-delete
    accessModes:
      - ReadWriteOnce
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  nodeSelector:
    kubernetes.io/hostname: node3

# Metrics configuration
metrics:
  enabled: false
  serviceMonitor:
    enabled: false

# Network configuration
# service:
#   type: ClusterIP
#   ports:
#     postgresql: 5432

# Security context
# securityContext:
#   enabled: true
#   fsGroup: 1001

# Backup configuration (optional)
backup:
  enabled: false

# Monitoring
monitoring:
  enabled: false
