---
- name: Полная настройка Kubernetes кластера
  hosts: kubernetes
  gather_facts: yes
  become: no

  tasks:
    - name: Установка nginx-ingress
      include: 00-nginx-ingress/00-install-ingress-nginx.yml

    - name: Установка cert-manager
      include: 01-cert-manager/01-install-cert-manager.yml

    - name: Установка local path provisioner
      include: 03-local-path-provisioner/03-install-local-path-provisioner-manifests.yml

    - name: Установка ArgoCD
      include: 02-argocd/02-install-argocd.yml

    - name: Итоговая информация
      debug:
        msg: |
          🎉 Все компоненты установлены успешно!
          
          📋 Установленные компоненты:
          - nginx-ingress (входящий трафик)
          - cert-manager (управление TLS сертификатами)
          - local-path-provisioner (локальное хранилище)
          - ArgoCD (GitOps)
          
          🔗 Доступ к ArgoCD:
          - HTTPS: смотрите вывод задачи "Вывод информации о доступе к ArgoCD" выше
            (домен берётся из 02-argocd/argocd-values.yaml -> global.domain)
          
          🌐 Ingress Controller:
          - IngressClass: nginx
          - Namespace: ingress-nginx
