---
- name: Установка local path provisioner (через манифесты)
  hosts: kubernetes
  gather_facts: yes
  become: no
  vars:
    local_path_provisioner_version: "v0.0.32"
    local_path_provisioner_manifest_url: "https://raw.githubusercontent.com/rancher/local-path-provisioner/{{ local_path_provisioner_version }}/deploy/local-path-storage.yaml"

  tasks:
    - name: Скачивание манифеста local-path-provisioner
      uri:
        url: "{{ local_path_provisioner_manifest_url }}"
        method: GET
        return_content: yes
      register: manifest_content

    - name: Применение манифеста local-path-provisioner
      kubernetes.core.k8s:
        state: present
        definition: "{{ manifest_content.content | from_yaml_all | list }}"

    - name: Ожидание готовности local-path-provisioner
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: local-path-provisioner
        namespace: local-path-storage
        wait: true
        wait_condition:
          type: Available
          status: "True"
        wait_timeout: 300

    - name: Получение информации о StorageClass
      kubernetes.core.k8s_info:
        api_version: storage.k8s.io/v1
        kind: StorageClass
        name: local-path
      register: storageclass_info

    - name: Вывод информации о local-path-provisioner
      debug:
        msg: |
          local-path-provisioner установлен успешно!
          Namespace: local-path-storage
          Версия: {{ local_path_provisioner_version }}
          StorageClass: local-path (по умолчанию)
          Путь для хранения: /opt/local-path-provisioner
          Reclaim Policy: {{ storageclass_info.resources[0].reclaimPolicy if storageclass_info.resources else 'Delete' }}
          Volume Binding: {{ storageclass_info.resources[0].volumeBindingMode if storageclass_info.resources else 'WaitForFirstConsumer' }}

        #мб добавить удаление созданного по дефолту storageCLass. Или мб можно как-то -set передать в apply там?
