---
- name: Установка local path provisioner (через Helm)
  hosts: kubernetes
  gather_facts: yes
  become: no
  vars:
    local_path_provisioner_version: "v0.0.32"
    local_path_provisioner_repo: "https://github.com/rancher/local-path-provisioner.git"
    local_path_provisioner_chart_path: "./deploy/chart/local-path-provisioner"
    local_path_provisioner_values_file: "{{ playbook_dir }}/local-path-provisioner-values.yaml"

  tasks:
    - name: Клонирование репозитория local-path-provisioner
      git:
        repo: "{{ local_path_provisioner_repo }}"
        dest: "/tmp/local-path-provisioner"
        version: "{{ local_path_provisioner_version }}"
        force: yes

    - name: Создание namespace local-path-provisioner
      kubernetes.core.k8s:
        name: local-path-provisioner
        api_version: v1
        kind: Namespace
        state: present


    - name: Установка local-path-provisioner через Helm
      kubernetes.core.helm:
        name: local-path-storage
        chart_ref: "/tmp/local-path-provisioner/{{ local_path_provisioner_chart_path }}"
        release_namespace: local-path-provisioner
        values_files:
          - "{{ local_path_provisioner_values_file }}"
        state: present
        wait: true
        wait_timeout: "5m"

    - name: Проверка статуса local-path-provisioner
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: local-path-provisioner
        namespace: local-path-provisioner
      register: deployment_info

    - name: Вывод статуса Deployment
      debug:
        msg: |
          Deployment статус:
          Готовые поды: {{ deployment_info.resources[0].status.readyReplicas if deployment_info.resources else 'N/A' }}
          Всего подов: {{ deployment_info.resources[0].status.replicas if deployment_info.resources else 'N/A' }}
          Обновления: {{ deployment_info.resources[0].status.updatedReplicas if deployment_info.resources else 'N/A' }}

    - name: Получение информации о StorageClass
      kubernetes.core.k8s_info:
        api_version: storage.k8s.io/v1
        kind: StorageClass
        name: local-path
      register: storageclass_info

    - name: Вывод информации о local-path-provisioner
      debug:
        msg: |
          local-path-provisioner установлен успешно!
          Namespace: local-path-provisioner
          Версия: {{ local_path_provisioner_version }}
          StorageClass: local-path (по умолчанию)
          Путь для хранения: /opt/local-path-provisioner
          Reclaim Policy: {{ storageclass_info.resources[0].reclaimPolicy if storageclass_info.resources else 'Delete' }}
          Volume Binding: {{ storageclass_info.resources[0].volumeBindingMode if storageclass_info.resources else 'WaitForFirstConsumer' }}

    - name: Применение StorageClass local-path-delete
      kubernetes.core.k8s:
        state: present
        src: "{{ playbook_dir }}/local-path-storage-class-delete.yaml"

    - name: Диагностика подов local-path-provisioner
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: local-path-provisioner
        label_selectors:
          - "app.kubernetes.io/name=local-path-provisioner"
      register: provisioner_pods

    - name: Вывод статуса подов
      debug:
        msg: |
          Статус подов local-path-provisioner:
          {% for pod in provisioner_pods.resources %}
          Под: {{ pod.metadata.name }}
          Статус: {{ pod.status.phase }}
          Нода: {{ pod.spec.nodeName }}
          {% if pod.status.conditions %}
          Условия:
          {% for condition in pod.status.conditions %}
          - {{ condition.type }}: {{ condition.status }} ({{ condition.reason }})
          {% endfor %}
          {% endif %}
          {% endfor %}

    - name: Проверка событий кластера
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Event
        namespace: local-path-provisioner
      register: cluster_events

    - name: Вывод событий кластера
      debug:
        msg: |
          События кластера:
          {% for event in cluster_events.resources[-5:] %}
          {{ event.firstTimestamp }} - {{ event.type }}: {{ event.reason }} - {{ event.message }}
          {% endfor %}

    - name: Проверка всех StorageClass
      kubernetes.core.k8s_info:
        api_version: storage.k8s.io/v1
        kind: StorageClass
      register: all_storageclasses

    - name: Вывод всех StorageClass
      debug:
        msg: |
          Доступные StorageClass:
          {% for sc in all_storageclasses.resources %}
          - {{ sc.metadata.name }} (provisioner: {{ sc.provisioner }}, default: {{ sc.metadata.annotations.get('storageclass.kubernetes.io/is-default-class', 'false') }})
          {% endfor %}

    - name: Очистка временных файлов
      file:
        path: "/tmp/local-path-provisioner"
        state: absent

    # TODO добавить создание storage классов
