apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: local-path-test-pod
  namespace: default
spec:
  containers:
  - name: test-container
    image: busybox
    command: ['sh', '-c', 'echo "Hello from local-path storage!" > /data/test.txt && sleep 3600']
    volumeMounts:
    - name: local-path-volume
      mountPath: /data
  volumes:
  - name: local-path-volume
    persistentVolumeClaim:
      claimName: local-path-pvc

