
# просмотр дефолтных значений: https://artifacthub.io/packages/helm/containeroo/local-path-provisioner

storageClass:
  create: false

nodePathMap:
  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    paths:
      - /opt/local-path-provisioner
