apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-delete
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  nodePath: "/var/lib/local-path-provisioner/delete"
