apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster-store
  target:
    name: keycloak-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: keycloak/credentials
        property: admin-password

