# Values override for dev environment
replicaCount: 1

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: test-app.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /


