apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-credentials
  namespace: rabbitmq
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster-store
  target:
    name: rabbitmq-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: teams/backend/dev/transcriber/rabbitmq
        property: password


