apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/StepanLem/k8s-my-postinstall.git
      targetRevision: main
      path: store/vaultwarden/chart
      helm:
        valueFiles:
          - $values/envs/dev2/apps/vaultwarden/values-of-vaultwarden.yaml
    - repoURL: https://github.com/StepanLem/k8s-my-postinstall.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

