# helm show values vault --repo https://helm.releases.hashicorp.com > vault-fullvalues.yaml

# server:
#   enabled: true
#   ha:
#     enabled: false
#   dataStorage:
#     enabled: true
#     size: 1Gi
#   ingress:
#     enabled: true
#     ingressClassName: nginx
#     hosts:
#       - host: vault.veryred.ru
#         paths:
#           - /

# global:
#   tlsDisable: false

server:
  enabled: true

#   ha:
#     enabled: false

  # standalone:
  #   enabled: true
    # config: |-
    #   ui = true

    #   listener "tcp" {
    #     address           = "0.0.0.0:8200"
    #     tls_cert_file     = "/vault/tls/tls.crt"
    #     tls_key_file      = "/vault/tls/tls.key"
    #     tls_client_ca_file = "/vault/tls/ca.crt"
    #   }

    #   storage "raft" {
    #     path    = "/vault/data"
    #     node_id = "vault-0"
    #   }

    # По дефолту было:
    # storage "file" {
    #     path = "/vault/data"
    #   }

  # Это дефолтные значения
  # dataStorage:
  #   enabled: true
  #   storageClass: "standard"   # адаптируй к своему кластеру. Чтобы дефолтный - null
  #   size: 10Gi
  #   mountPath: "/vault/data"
  #   accessMode: ReadWriteOnce


  ingress:
    enabled: true
    ingressClassName: nginx
    # annotations:
    #   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #   nginx.ingress.kubernetes.io/ssl-passthrough: "true"  # ← TLS passthrough!
      # /cluster-issuer(или /issuer, если и тут поменять) должен быть создан заранее для проекта или для кластера соосвественно
      # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: vault.veryred.ru
    # tls:
    #   - secretName: vault-tls-secret
    #     hosts:
    #       - vault.veryred.ru

  # # Монтирование сертификатов в pod
  # volumes:
  #   - name: vault-tls
  #     secret:
  #       secretName: vault-tls-secret
  #       items:
  #         - key: tls.crt
  #           path: tls.crt
  #         - key: tls.key
  #           path: tls.key
  #         - key: ca.crt
  #           path: ca.crt

  # volumeMounts:
  #   - name: vault-tls
  #     mountPath: /vault/tls
  #     readOnly: true

  # standalone:
  #   enabled: true
  #   config: |-
  #     ui = true

  #     listener "tcp" {
  #       address = "[::]:8200"
  #       tls_cert_file = "/vault/tls/tls.crt"
  #       tls_key_file = "/vault/tls/tls.key"
  #       tls_client_ca_file = "/vault/tls/ca.crt"
  #     }

  #     storage "file" {
  #       path = "/vault/data"
  #     }
      
ui:
  enabled: true

# injector:
#   enabled: false