apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-dev-github
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/hashicorp/vault-helm.git
      targetRevision: v0.30.1
      path: .
      helm:
        valueFiles:
          - $values/envs/dev/apps/vault/values-of-vault.yaml
    - repoURL: https://github.com/StepanLem/k8s-my-postinstall.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
