apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "test-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "test-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "test-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: {{ include "test-app.fullname" . }}-html

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-app.fullname" . }}-html
  namespace: {{ .Release.Namespace }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Test App - Ingress Test</title>
        <style>
            body { 
                font-family: Arial, sans-serif; 
                margin: 40px; 
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
            }
            .container {
                text-align: center;
                background: rgba(255,255,255,0.1);
                padding: 40px;
                border-radius: 20px;
                backdrop-filter: blur(10px);
                box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
            }
            h1 { color: #fff; margin-bottom: 20px; }
            .status { 
                background: #4CAF50; 
                color: white; 
                padding: 10px 20px; 
                border-radius: 25px; 
                display: inline-block;
                margin: 10px;
            }
            .info { 
                background: rgba(255,255,255,0.2); 
                padding: 20px; 
                border-radius: 10px; 
                margin: 20px 0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 Test App - Ingress Test</h1>
            <div class="status">✅ Ingress работает!</div>
            <div class="info">
                <h3>Информация о подключении:</h3>
                <p><strong>Протокол:</strong> HTTP</p>
                <p><strong>Host:</strong> {{ .Values.ingress.host }}</p>
                <p><strong>Время:</strong> <span id="time"></span></p>
                <p><strong>Namespace:</strong> {{ .Release.Namespace }}</p>
            </div>
            <p>Если вы видите эту страницу, значит nginx-ingress работает корректно! 🎉</p>
        </div>
        <script>
            document.getElementById('time').textContent = new Date().toLocaleString();
        </script>
    </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-app.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "test-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    {{- include "test-app.selectorLabels" . | nindent 4 }}
