apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts  # без oci и имени
      chart: rabbitmq
      targetRevision: 16.0.14 # chart-version
      helm:
        valueFiles:
          - $values/envs/dev/apps/rabbitmq/values-of-rabbitmq.yaml
    - repoURL: https://github.com/StepanLem/k8s-my-postinstall.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
