apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: postgres
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster-store
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: teams/devops/pg-creds/dev
        property: admin-password
    - secretKey: user-password # инфо об этом в global.postgresql.auth. Без подаукаунт и подбазы - не реаботает никак.
      remoteRef:
        key: teams/backend/dev/transcriber/bd/svc-main-backend
        property: database-password

