apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-portforward-default
  namespace: default # доступ к namespace default для transcriber приложений
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""] 
    resources: ["pods/portforward"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
