apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    name: in-cluster # значит https://kubernetes.default.svc
  source:
    repoURL: https://github.com/StepanLem/k8s-my-postinstall.git
    targetRevision: vault # branch name
    path: envs/dev/apps
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true