apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: keycloak
      targetRevision: 25.2.0 # chart-version
      helm:
        valueFiles:
          - $values/envs/dev2/apps/keycloak/values-of-keycloak.yaml
    - repoURL: https://github.com/StepanLem/k8s-my-postinstall.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


