apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: postgres
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster-store
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: postgres/credentials
        property: password
    - secretKey: postgres-username
      remoteRef:
        key: postgres/credentials
        property: username
    - secretKey: postgres-database
      remoteRef:
        key: postgres/credentials
        property: database
