apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv/veryred"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "default" 
          key: "token"