---
- name: Установка External Secrets Operator
  hosts: kubernetes
  gather_facts: yes
  become: no
  vars:
    eso_version: "0.16.2" # https://external-secrets.io/latest/introduction/stability-support/
    eso_values_file: "eso-values.yaml"

  tasks:
    - name: Проверка Helm
      command: "helm version"
      register: helm_check
      failed_when: helm_check.rc != 0
      changed_when: false

    - name: Добавление Helm репозитория External Secrets
      kubernetes.core.helm_repository:
        name: external-secrets
        repo_url: https://charts.external-secrets.io

    - name: Установка External Secrets Operator
      kubernetes.core.helm:
        name: external-secrets-operator
        chart_ref: external-secrets/external-secrets
        chart_version: "{{ eso_version }}"
        release_namespace: external-secrets
        create_namespace: true
        values_files:
          - "{{ eso_values_file }}"

    - name: Ожидание готовности External Secrets Operator
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: external-secrets-operator
        namespace: external-secrets
        wait: true
        wait_condition:
          type: Available
          status: "True"
        wait_timeout: 300

    # - name: Применение ESO ресурсов
    #   kubernetes.core.k8s:
    #     state: present
    #     definition: "{{ lookup('file', item) | from_yaml }}"
    #   loop:
    #     - "cluster-secret-store.yaml"

    # - name: Вывод информации о External Secrets Operator
    #   debug:
    #     msg: |
    #       External Secrets Operator установлен успешно!
    #       Namespace: external-secrets
    #       Версия: {{ eso_version }}
    #       CRDs установлены автоматически
    #       Доступные ресурсы:
    #       - SecretStore
    #       - ClusterSecretStore  
    #       - ExternalSecret
    #       - ClusterExternalSecret
