apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200" # понять как формируется ссылка
      path: "kv/veryred"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: external-secrets
          # ТЕБЕ НАДО СОЗДАТЬ ЭТОТ секрет. Вот так:
# kubectl create secret generic vault-token \
#   -n external-secrets \
#   --from-literal=token=hvs....
# Но лучше не использовать рут-токен, а создать policy с минимальными правами. Гугли.