apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-store
spec:
  provider:
    vault:
      server: "https://vault.veryred.ru" # понять как формируется ссылка внутри кластера и написать здесь.
      path: "kv/veryred"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: external-secrets
          # ТЕБЕ НАДО СОЗДАТЬ ЭТОТ секрет. Вот так:
# kubectl create secret generic vault-token \
#   -n external-secrets \
#   --from-literal=token=hvs....
# Но лучше не использовать рут-токен, а создать policy с минимальными правами. Гугли.



# Команды поочереди:

# Для пересоздания: k delete ClusterSecretStore/vault-cluster-store
# Для пересоздания: k delete secret/vault-token -n external-secrets

# kubectl create secret generic vault-token \
#   -n external-secrets \
#   --from-literal=token=hvs....

# k apply -f 04-external-secrets-operator/cluster-secret-store.yaml 
