apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
  namespace: external-secrets # у будущего секрета будет такой же namespace
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster-store
  target:
    name: example-secret # это имя будущего секрета
    creationPolicy: Owner
  data:
    - secretKey: token # это data(aka propery/key) будущего секрета
      remoteRef:
        key: test-secret # это path секрета в волте
        property: token # это data(aka propery/key) секрета в волте
