apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster-store
  target:
    name: example-secret
    creationPolicy: Owner
  data:
    - secretKey: my-key
      remoteRef:
        key: secret/data/my-app
        property: my-key
