# Default values for test-app
replicaCount: 2

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: nginx
  host: test-app.veryred.ru
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
