apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.10.0 # chart-version
      helm:
        valueFiles:
          - $values/envs/dev2/apps/longhorn/values-of-longhorn.yaml
    - repoURL: https://github.com/StepanLem/k8s-my-postinstall.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system # обязательно именно в этот namespace - официальное требование
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

